repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args:
        - '--max-line-length=88'
        - '--exclude=test_mysd2csv.py,conftest.py'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        name: mypy (santa)
        additional_dependencies: [types-all]
        args: [
          '--ignore-missing-imports',
          '--namespace-packages',
          '--explicit-package-bases'
        ]
